high-level API for ConvexMesh, TriangleMesh, HeightField
EmbarkStudios/physx-rs pull request #195
Opened 2023-03-27 08:06 UTC by rlidwka

I'm working on physx-bevy integration [plugin](https://github.com/rlidwka/bevy_physx), and I need tools to visualize all shapes on the screen for debugging purposes. Using physx-sys API quickly turned into nightmare with pointers, so I wrote API to abstract all that.

This PR is relatively straightforward porting of all methods in [PxTriangleMesh](https://nvidia-omniverse.github.io/PhysX/physx/5.1.3/_build/physx/latest/class_px_triangle_mesh.html), [PxHeightField](https://nvidia-omniverse.github.io/PhysX/physx/5.1.3/_build/physx/latest/class_px_height_field.html) and [PxConvexMesh](https://nvidia-omniverse.github.io/PhysX/physx/5.1.3/_build/physx/latest/file_include_geometry_PxConvexMesh.h.html) classes (with the exception of new SDFs getters from physx 5.1, which I didn't get around to).

2023-04-24 03:45 UTC, rlidwka commented
I've rebased commit from current `main` branch, and fixed failed lint checks.

2023-07-22 16:08 UTC, rlidwka commented on physx/src/triangle_mesh.rs
> +    pub fn get_vertices_for_modification(&mut self) -> &mut [PxVec3] {
Name copied from PhysX as is.

I didn't even notice that TriangleMesh has two similar functions (`PxTriangleMesh_getVertices`, `PxTriangleMesh_getVerticesForModification_mut`) that seemingly only differ in mutability.

What is the actual difference between those?

On one hand, Rust has a convention for these, and C++ doesn't. On the other hand, people reading original physx docs might get confused.

Not sure, but `get_vertices_mut()` looks like a good idea.

2023-08-23 07:03 UTC, tgolsson commented on physx/src/triangle_mesh.rs
> +    pub fn get_vertices_for_modification(&mut self) -> &mut [PxVec3] {
> I didn't even notice that TriangleMesh has two similar functions (PxTriangleMesh_getVertices, PxTriangleMesh_getVerticesForModification_mut) that seemingly only differ in mutability.

The only difference is that one returns `const *Vec3` and the other one is `*Vec3`, and have the matching requirement on the target. I think this one makes more sense as `get_vertices_mut`, and maybe a reference to the PhysX name in the doc comment!

2023-08-30 09:50 UTC, tgolsson requested changes
@rlidwka Sorry for getting this stuck, let's try to get it merged before next release as well? I've merged main so just some nits I found with unnecessary/overly broad transmutes.

2023-08-30 09:50 UTC, tgolsson commented on physx/src/convex_mesh.rs
> +        unsafe { std::mem::transmute(vertices) }
Couldn't we cast the pointer and construct the slice with the right type? Just fewer things being casted.

2023-08-30 09:50 UTC, tgolsson commented on physx/src/height_field.rs
> +                std::mem::transmute(&*PxHeightField_getSample(self.as_ptr(), row, column))
I think same as above here; can cast the pointer to avoid the transmute?

2023-08-30 09:50 UTC, tgolsson commented on physx/src/triangle_mesh.rs
> +        unsafe { std::mem::transmute(vertices) }
And here

2023-08-30 12:12 UTC, rlidwka commented
> I've merged main so just some nits I found with unnecessary/overly broad transmutes.

@tgolsson, transmutes fixed in https://github.com/EmbarkStudios/physx-rs/pull/195/commits/e14cf92c2f2ca26d93151fd69e7d37d7d863e47e

2023-08-30 14:32 UTC, tgolsson approved these changes
Thanks @rlidwka!

2023-08-30 14:37 UTC, merged