Support building for Android on aarch64 macOS hosts
EmbarkStudios/physx-rs pull request #216
Opened 2023-10-09 20:53 UTC by fornwall

The NDK puts universal binaries under the `darwin-x86_64` directory.

Verified that it works by patching Cargo.toml to use this branch while building on an M1 macbook.

2023-10-09 21:07 UTC, fornwall commented
The build error is a new clippy lint, fixed by https://github.com/EmbarkStudios/physx-rs/pull/217

2023-10-10 07:42 UTC, tgolsson approved these changes

2023-10-10 07:42 UTC, tgolsson requested changes
Actually, changelogs. Then OK.

2023-10-10 07:53 UTC, tgolsson approved these changes

2023-10-10 07:55 UTC, fornwall commented
@tgolsson Thanks, added a changelog entry now.

2023-10-10 08:07 UTC, merged